sna: sna_damage: fix missing include of extinit.h
> sna_video.c: In function 'sna_video_init':
> sna_video.c:956:13: error: 'noXvExtension' undeclared (first use in this function); did you mean 'XvExtension'?
>   956 |         if (noXvExtension)
>       |             ^~~~~~~~~~~~~
>       |             XvExtension

Signed-off-by: Enrico Weigelt, metux IT consult <info@metux.net>